using BlazeUI.Headless.Components.Field;
using BlazeUI.Headless.Components.Form;
using Bunit;
using Microsoft.AspNetCore.Components;
using InputComponent = BlazeUI.Headless.Components.Input.Input;

namespace BlazeUI.Headless.Tests.Components.Field;

public class FieldTests : BunitContext
{
    // ─── FieldRoot ───────────────────────────────────────────────────────────────

    [Fact]
    public void Root_RendersDefaultDivTag()
    {
        var cut = Render<FieldRoot>();
        Assert.Equal("DIV", cut.Find("div").TagName);
    }

    [Fact]
    public void Root_DataValidPresentByDefault()
    {
        var cut = Render<FieldRoot>();
        Assert.NotNull(cut.Find("[data-valid]"));
        Assert.Empty(cut.FindAll("[data-invalid]"));
    }

    [Fact]
    public void Root_DataInvalidWhenInvalidParameterSet()
    {
        var cut = Render<FieldRoot>(p => p.Add(c => c.Invalid, true));
        Assert.NotNull(cut.Find("[data-invalid]"));
        Assert.Empty(cut.FindAll("[data-valid]"));
    }

    [Fact]
    public void Root_DataDisabledWhenDisabled()
    {
        var cut = Render<FieldRoot>(p => p.Add(c => c.Disabled, true));
        Assert.NotNull(cut.Find("[data-disabled]"));
    }

    [Fact]
    public void Root_NoDataDisabledWhenEnabled()
    {
        var cut = Render<FieldRoot>();
        Assert.Empty(cut.FindAll("[data-disabled]"));
    }

    // ─── FieldLabel ──────────────────────────────────────────────────────────────

    [Fact]
    public void Label_RendersLabelElement()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Name")));

        Assert.Equal("LABEL", cut.Find("label").TagName);
    }

    [Fact]
    public void Label_ForAttributeReferencesControlId()
    {
        // The label's `for` attribute must match the auto-generated control ID so that
        // clicking the label activates the associated control.
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Name")));

        var forAttr = cut.Find("label").GetAttribute("for");
        Assert.NotNull(forAttr);
        Assert.Contains("field-control", forAttr);
    }

    [Fact]
    public void Label_HasIdAttribute()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Name")));

        var id = cut.Find("label").GetAttribute("id");
        Assert.NotNull(id);
        Assert.False(string.IsNullOrEmpty(id));
    }

    [Fact]
    public void Label_AllStateDataAttributesPropagatedFromRoot()
    {
        // When the root is disabled and invalid, all state attributes flow to the label.
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Disabled, true)
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Email")));

        var label = cut.Find("label");
        Assert.NotNull(label.GetAttribute("data-disabled"));
        Assert.NotNull(label.GetAttribute("data-invalid"));
        Assert.Empty(cut.FindAll("label[data-valid]"));
    }

    // ─── FieldDescription ────────────────────────────────────────────────────────

    [Fact]
    public void Description_RendersParagraphElement()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Helper text")));

        Assert.Equal("P", cut.Find("p").TagName);
    }

    [Fact]
    public void Description_HasAutoGeneratedId()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Helper")));

        var id = cut.Find("p").GetAttribute("id");
        Assert.NotNull(id);
        Assert.Contains("field-description", id);
    }

    [Fact]
    public void Description_AllStateDataAttributesPropagated()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Disabled, true)
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Hint")));

        var desc = cut.Find("p");
        Assert.NotNull(desc.GetAttribute("data-disabled"));
        Assert.NotNull(desc.GetAttribute("data-invalid"));
        Assert.Empty(cut.FindAll("p[data-valid]"));
    }

    // ─── FieldControl ────────────────────────────────────────────────────────────

    [Fact]
    public void Control_RendersInputElement()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldControl>());

        Assert.Equal("INPUT", cut.Find("input").TagName);
    }

    [Fact]
    public void Control_IdMatchesLabelForAttribute()
    {
        // The control's id must match the label's `for` attribute for native label wiring.
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Name"))
            .AddChildContent<FieldControl>());

        var controlId = cut.Find("input").GetAttribute("id");
        var forAttr = cut.Find("label").GetAttribute("for");

        Assert.NotNull(controlId);
        Assert.Equal(forAttr, controlId);
    }

    [Fact]
    public void Control_AriaInvalidPresentWhenInvalid()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldControl>());

        Assert.Equal("true", cut.Find("input").GetAttribute("aria-invalid"));
    }

    [Fact]
    public void Control_NoAriaInvalidWhenValid()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldControl>());

        Assert.Null(cut.Find("input").GetAttribute("aria-invalid"));
    }

    [Fact]
    public void Control_AriaDescribedByIncludesDescriptionId()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Hint"))
            .AddChildContent<FieldControl>());

        var descriptionId = cut.Find("p").GetAttribute("id");
        var describedBy = cut.Find("input").GetAttribute("aria-describedby");

        Assert.NotNull(descriptionId);
        Assert.NotNull(describedBy);
        Assert.Contains(descriptionId!, describedBy!);
    }

    [Fact]
    public void Control_AriaDescribedByIncludesErrorIdWhenInvalid()
    {
        // When the field is invalid, the error's ID must appear in aria-describedby.
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Hint"))
            .AddChildContent<FieldControl>()
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Required")));

        var errorId = cut.Find("[aria-live]").GetAttribute("id");
        var describedBy = cut.Find("input").GetAttribute("aria-describedby");

        Assert.NotNull(errorId);
        Assert.NotNull(describedBy);
        Assert.Contains(errorId!, describedBy!);
    }

    [Fact]
    public void Control_AriaDescribedByExcludesErrorIdWhenValid()
    {
        // The error ID must not appear in aria-describedby when the field is valid.
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Hint"))
            .AddChildContent<FieldControl>()
            .AddChildContent<FieldError>(ep => ep
                .Add(c => c.KeepMounted, true)
                .AddChildContent("Required")));

        var describedBy = cut.Find("input").GetAttribute("aria-describedby");

        if (describedBy is not null)
        {
            // Must not contain the error element's id when valid.
            var errorId = cut.Find("[aria-live]").GetAttribute("id");
            Assert.DoesNotContain(errorId!, describedBy);
        }
    }

    [Fact]
    public void Control_AriaLabelledByReferencesLabelId()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Username"))
            .AddChildContent<FieldControl>());

        var labelId = cut.Find("label").GetAttribute("id");
        var labelledBy = cut.Find("input").GetAttribute("aria-labelledby");

        Assert.NotNull(labelId);
        Assert.Equal(labelId, labelledBy);
    }

    [Fact]
    public void Control_NameAttributeFromFieldRoot()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Name, "email")
            .AddChildContent<FieldControl>());

        Assert.Equal("email", cut.Find("input").GetAttribute("name"));
    }

    [Fact]
    public void Control_AllStateDataAttributesPropagated()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Disabled, true)
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldControl>());

        var input = cut.Find("input");
        Assert.NotNull(input.GetAttribute("data-disabled"));
        Assert.NotNull(input.GetAttribute("data-invalid"));
        Assert.Empty(cut.FindAll("input[data-valid]"));
    }

    // ─── FieldError ──────────────────────────────────────────────────────────────

    [Fact]
    public void Error_NotRenderedWhenValid()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Error")));

        Assert.Empty(cut.FindAll("[aria-live]"));
    }

    [Fact]
    public void Error_RenderedWhenInvalid()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Error message")));

        var error = cut.Find("[aria-live]");
        Assert.Equal("polite", error.GetAttribute("aria-live"));
        Assert.Contains("Error message", error.TextContent);
    }

    [Fact]
    public void Error_KeepMountedRendersWhenValid()
    {
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldError>(ep => ep
                .Add(c => c.KeepMounted, true)
                .AddChildContent("Error")));

        Assert.NotEmpty(cut.FindAll("[aria-live]"));
    }

    [Fact]
    public void Error_HasAutoGeneratedId()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Error")));

        var id = cut.Find("[aria-live]").GetAttribute("id");
        Assert.NotNull(id);
        Assert.Contains("field-error", id);
    }

    [Fact]
    public void Error_AllStateDataAttributesPropagated()
    {
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .Add(c => c.Disabled, true)
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Error")));

        var error = cut.Find("[aria-live]");
        Assert.NotNull(error.GetAttribute("data-disabled"));
        Assert.NotNull(error.GetAttribute("data-invalid"));
        Assert.Empty(cut.FindAll("[aria-live][data-valid]"));
    }

    // ─── FieldValidity ───────────────────────────────────────────────────────────

    [Fact]
    public void Validity_ExposesValidStateToChildContent()
    {
        FieldValidityState? capturedState = null;

        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldValidity>(vp => vp
                .Add(c => c.ChildContent, (RenderFragment<FieldValidityState>)(s => b =>
                {
                    capturedState = s;
                }))));

        Assert.NotNull(capturedState);
        Assert.True(capturedState!.Value.Valid);
        Assert.False(capturedState.Value.Invalid);
    }

    [Fact]
    public void Validity_ExposesInvalidStateWhenFieldInvalid()
    {
        FieldValidityState? capturedState = null;

        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldValidity>(vp => vp
                .Add(c => c.ChildContent, (RenderFragment<FieldValidityState>)(s => b =>
                {
                    capturedState = s;
                }))));

        Assert.NotNull(capturedState);
        Assert.False(capturedState!.Value.Valid);
        Assert.True(capturedState.Value.Invalid);
    }

    [Fact]
    public void Validity_ExposesFocusedAndFilledState()
    {
        // FieldValidityState must include Focused and Filled for completeness.
        var state = new FieldValidityState(
            Valid: true, Invalid: false, Dirty: false, Touched: false,
            Disabled: false, Focused: true, Filled: true);

        Assert.True(state.Focused);
        Assert.True(state.Filled);
    }

    // ─── FieldItem ───────────────────────────────────────────────────────────────

    [Fact]
    public void Item_RendersDivElement()
    {
        var cut = Render<FieldItem>();
        Assert.Equal("DIV", cut.Find("div").TagName);
    }

    [Fact]
    public void Item_DataDisabledWhenDisabled()
    {
        var cut = Render<FieldItem>(p => p.Add(c => c.Disabled, true));
        Assert.NotNull(cut.Find("[data-disabled]"));
    }

    [Fact]
    public void Item_NoDataDisabledWhenEnabled()
    {
        var cut = Render<FieldItem>();
        Assert.Empty(cut.FindAll("[data-disabled]"));
    }

    [Fact]
    public void Item_InheritsDisabledFromParentFieldRoot()
    {
        // When FieldRoot is disabled, nested FieldItem must also be disabled.
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Disabled, true)
            .AddChildContent<FieldItem>());

        Assert.NotNull(cut.Find("[data-disabled]"));
    }

    [Fact]
    public void Item_CascadesItemContext()
    {
        // FieldItem must cascade a FieldItemContext with the correct disabled state
        // so that nested controls can observe it.
        FieldItemContext? capturedContext = null;

        var cut = Render<FieldItem>(p => p
            .Add(c => c.Disabled, true)
            .AddChildContent(b =>
            {
                b.OpenComponent<ContextCapture>(0);
                b.AddComponentParameter(1, nameof(ContextCapture.OnCapture),
                    (Action<FieldItemContext?>)(ctx => capturedContext = ctx));
                b.CloseComponent();
            }));

        Assert.NotNull(capturedContext);
        Assert.True(capturedContext!.Disabled);
    }

    // ─── Cross-component wiring ───────────────────────────────────────────────────

    [Fact]
    public void DisabledStatePropagatesFromRootToAllChildren()
    {
        // The disabled state from FieldRoot flows into all child components via context.
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Disabled, true)
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Label"))
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Desc"))
            .AddChildContent<FieldControl>()
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Err")));

        // Root itself
        Assert.NotNull(cut.Find("div[data-disabled]"));
        // Label
        Assert.NotNull(cut.Find("label[data-disabled]"));
        // Description
        Assert.NotNull(cut.Find("p[data-disabled]"));
        // Control
        Assert.NotNull(cut.Find("input[data-disabled]"));
        // Error (rendered because Invalid is true)
        Assert.NotNull(cut.Find("[aria-live][data-disabled]"));
    }

    [Fact]
    public void LabelDescriptionErrorAllShareSameControlId()
    {
        // The control, label `for`, and aria-describedby must all reference the same ID.
        var cut = Render<FieldRoot>(p => p
            .Add(c => c.Invalid, true)
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Name"))
            .AddChildContent<FieldDescription>(dp => dp.AddChildContent("Hint"))
            .AddChildContent<FieldControl>()
            .AddChildContent<FieldError>(ep => ep.AddChildContent("Err")));

        var controlId = cut.Find("input").GetAttribute("id");
        var labelFor = cut.Find("label").GetAttribute("for");

        Assert.Equal(controlId, labelFor);
    }

    // ─── Consumer ID override ─────────────────────────────────────────────────

    [Fact]
    public void Input_ConsumerIdOverride_PropagatedToLabel()
    {
        // When a consumer provides an explicit id on Input inside a Field,
        // the rendered FieldLabel must emit a matching `for` attribute.
        var cut = Render<FieldRoot>(p => p
            .AddChildContent<FieldLabel>(lp => lp.AddChildContent("Username"))
            .AddChildContent<InputComponent>(ip => ip.Add(c => c.Id, "my-input")));

        var labelFor = cut.Find("label").GetAttribute("for");
        var inputId = cut.Find("input").GetAttribute("id");

        Assert.Equal("my-input", inputId);
        Assert.Equal("my-input", labelFor);
    }

    [Fact]
    public void FieldLabel_ConsumerForOverride_Respected()
    {
        // When a consumer provides an explicit `for` on FieldLabel, it should
        // take precedence over the context-derived ControlId.
        var cut = Render(builder =>
        {
            builder.OpenComponent<FieldRoot>(0);
            builder.AddComponentParameter(1, "ChildContent", (RenderFragment)(b =>
            {
                b.OpenComponent<FieldLabel>(0);
                b.AddComponentParameter(1, "ChildContent", (RenderFragment)(t =>
                    t.AddContent(0, "Username")));
                b.AddMultipleAttributes(2, new Dictionary<string, object> { ["for"] = "custom-control" });
                b.CloseComponent();
            }));
            builder.CloseComponent();
        });

        Assert.Equal("custom-control", cut.Find("label").GetAttribute("for"));
    }

    // Helper component that captures the FieldItemContext cascading value.
    private class ContextCapture : ComponentBase
    {
        [CascadingParameter]
        internal FieldItemContext? Context { get; set; }

        [Parameter]
        public Action<FieldItemContext?>? OnCapture { get; set; }

        protected override void OnParametersSet()
        {
            OnCapture?.Invoke(Context);
        }
    }
}
