/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TypographyRouteImport } from "./routes/typography"
import { Route as TooltipRouteImport } from "./routes/tooltip"
import { Route as ToggleGroupRouteImport } from "./routes/toggle-group"
import { Route as ToggleRouteImport } from "./routes/toggle"
import { Route as ToastRouteImport } from "./routes/toast"
import { Route as TextareaRouteImport } from "./routes/textarea"
import { Route as TabsRouteImport } from "./routes/tabs"
import { Route as TableRouteImport } from "./routes/table"
import { Route as SwitchRouteImport } from "./routes/switch"
import { Route as SpinnerRouteImport } from "./routes/spinner"
import { Route as SliderRouteImport } from "./routes/slider"
import { Route as SkeletonRouteImport } from "./routes/skeleton"
import { Route as SidebarRouteImport } from "./routes/sidebar"
import { Route as SheetRouteImport } from "./routes/sheet"
import { Route as SeparatorRouteImport } from "./routes/separator"
import { Route as SelectRouteImport } from "./routes/select"
import { Route as ScrollAreaRouteImport } from "./routes/scroll-area"
import { Route as RadioRouteImport } from "./routes/radio"
import { Route as ProgressRouteImport } from "./routes/progress"
import { Route as PreviewCardRouteImport } from "./routes/preview-card"
import { Route as PopoverRouteImport } from "./routes/popover"
import { Route as PaginationRouteImport } from "./routes/pagination"
import { Route as NavigationMenuRouteImport } from "./routes/navigation-menu"
import { Route as NativeSelectRouteImport } from "./routes/native-select"
import { Route as MenubarRouteImport } from "./routes/menubar"
import { Route as MenuRouteImport } from "./routes/menu"
import { Route as LabelRouteImport } from "./routes/label"
import { Route as KbdRouteImport } from "./routes/kbd"
import { Route as ItemRouteImport } from "./routes/item"
import { Route as InputOtpRouteImport } from "./routes/input-otp"
import { Route as InputGroupRouteImport } from "./routes/input-group"
import { Route as InputRouteImport } from "./routes/input"
import { Route as FieldRouteImport } from "./routes/field"
import { Route as EmptyRouteImport } from "./routes/empty"
import { Route as DrawerRouteImport } from "./routes/drawer"
import { Route as DialogRouteImport } from "./routes/dialog"
import { Route as ContextMenuRouteImport } from "./routes/context-menu"
import { Route as ComboboxRouteImport } from "./routes/combobox"
import { Route as CollapsibleRouteImport } from "./routes/collapsible"
import { Route as CheckboxRouteImport } from "./routes/checkbox"
import { Route as CardRouteImport } from "./routes/card"
import { Route as ButtonGroupRouteImport } from "./routes/button-group"
import { Route as ButtonRouteImport } from "./routes/button"
import { Route as BreadcrumbRouteImport } from "./routes/breadcrumb"
import { Route as BlocksRouteImport } from "./routes/blocks"
import { Route as BadgeRouteImport } from "./routes/badge"
import { Route as AvatarRouteImport } from "./routes/avatar"
import { Route as AspectRatioRouteImport } from "./routes/aspect-ratio"
import { Route as AlertDialogRouteImport } from "./routes/alert-dialog"
import { Route as AlertRouteImport } from "./routes/alert"
import { Route as AccordionRouteImport } from "./routes/accordion"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BlocksSidebar07RouteImport } from "./routes/blocks/sidebar-07"
import { Route as BlocksSidebar01RouteImport } from "./routes/blocks/sidebar-01"
import { Route as BlocksLogin02RouteImport } from "./routes/blocks/login-02"

const TypographyRoute = TypographyRouteImport.update({
  id: "/typography",
  path: "/typography",
  getParentRoute: () => rootRouteImport,
} as any)
const TooltipRoute = TooltipRouteImport.update({
  id: "/tooltip",
  path: "/tooltip",
  getParentRoute: () => rootRouteImport,
} as any)
const ToggleGroupRoute = ToggleGroupRouteImport.update({
  id: "/toggle-group",
  path: "/toggle-group",
  getParentRoute: () => rootRouteImport,
} as any)
const ToggleRoute = ToggleRouteImport.update({
  id: "/toggle",
  path: "/toggle",
  getParentRoute: () => rootRouteImport,
} as any)
const ToastRoute = ToastRouteImport.update({
  id: "/toast",
  path: "/toast",
  getParentRoute: () => rootRouteImport,
} as any)
const TextareaRoute = TextareaRouteImport.update({
  id: "/textarea",
  path: "/textarea",
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: "/tabs",
  path: "/tabs",
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: "/table",
  path: "/table",
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchRoute = SwitchRouteImport.update({
  id: "/switch",
  path: "/switch",
  getParentRoute: () => rootRouteImport,
} as any)
const SpinnerRoute = SpinnerRouteImport.update({
  id: "/spinner",
  path: "/spinner",
  getParentRoute: () => rootRouteImport,
} as any)
const SliderRoute = SliderRouteImport.update({
  id: "/slider",
  path: "/slider",
  getParentRoute: () => rootRouteImport,
} as any)
const SkeletonRoute = SkeletonRouteImport.update({
  id: "/skeleton",
  path: "/skeleton",
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: "/sidebar",
  path: "/sidebar",
  getParentRoute: () => rootRouteImport,
} as any)
const SheetRoute = SheetRouteImport.update({
  id: "/sheet",
  path: "/sheet",
  getParentRoute: () => rootRouteImport,
} as any)
const SeparatorRoute = SeparatorRouteImport.update({
  id: "/separator",
  path: "/separator",
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: "/select",
  path: "/select",
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollAreaRoute = ScrollAreaRouteImport.update({
  id: "/scroll-area",
  path: "/scroll-area",
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: "/radio",
  path: "/radio",
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: "/progress",
  path: "/progress",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCardRoute = PreviewCardRouteImport.update({
  id: "/preview-card",
  path: "/preview-card",
  getParentRoute: () => rootRouteImport,
} as any)
const PopoverRoute = PopoverRouteImport.update({
  id: "/popover",
  path: "/popover",
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationRoute = PaginationRouteImport.update({
  id: "/pagination",
  path: "/pagination",
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationMenuRoute = NavigationMenuRouteImport.update({
  id: "/navigation-menu",
  path: "/navigation-menu",
  getParentRoute: () => rootRouteImport,
} as any)
const NativeSelectRoute = NativeSelectRouteImport.update({
  id: "/native-select",
  path: "/native-select",
  getParentRoute: () => rootRouteImport,
} as any)
const MenubarRoute = MenubarRouteImport.update({
  id: "/menubar",
  path: "/menubar",
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: "/label",
  path: "/label",
  getParentRoute: () => rootRouteImport,
} as any)
const KbdRoute = KbdRouteImport.update({
  id: "/kbd",
  path: "/kbd",
  getParentRoute: () => rootRouteImport,
} as any)
const ItemRoute = ItemRouteImport.update({
  id: "/item",
  path: "/item",
  getParentRoute: () => rootRouteImport,
} as any)
const InputOtpRoute = InputOtpRouteImport.update({
  id: "/input-otp",
  path: "/input-otp",
  getParentRoute: () => rootRouteImport,
} as any)
const InputGroupRoute = InputGroupRouteImport.update({
  id: "/input-group",
  path: "/input-group",
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: "/input",
  path: "/input",
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: "/field",
  path: "/field",
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoute = EmptyRouteImport.update({
  id: "/empty",
  path: "/empty",
  getParentRoute: () => rootRouteImport,
} as any)
const DrawerRoute = DrawerRouteImport.update({
  id: "/drawer",
  path: "/drawer",
  getParentRoute: () => rootRouteImport,
} as any)
const DialogRoute = DialogRouteImport.update({
  id: "/dialog",
  path: "/dialog",
  getParentRoute: () => rootRouteImport,
} as any)
const ContextMenuRoute = ContextMenuRouteImport.update({
  id: "/context-menu",
  path: "/context-menu",
  getParentRoute: () => rootRouteImport,
} as any)
const ComboboxRoute = ComboboxRouteImport.update({
  id: "/combobox",
  path: "/combobox",
  getParentRoute: () => rootRouteImport,
} as any)
const CollapsibleRoute = CollapsibleRouteImport.update({
  id: "/collapsible",
  path: "/collapsible",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckboxRoute = CheckboxRouteImport.update({
  id: "/checkbox",
  path: "/checkbox",
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: "/card",
  path: "/card",
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonGroupRoute = ButtonGroupRouteImport.update({
  id: "/button-group",
  path: "/button-group",
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: "/button",
  path: "/button",
  getParentRoute: () => rootRouteImport,
} as any)
const BreadcrumbRoute = BreadcrumbRouteImport.update({
  id: "/breadcrumb",
  path: "/breadcrumb",
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: "/blocks",
  path: "/blocks",
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeRoute = BadgeRouteImport.update({
  id: "/badge",
  path: "/badge",
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: "/avatar",
  path: "/avatar",
  getParentRoute: () => rootRouteImport,
} as any)
const AspectRatioRoute = AspectRatioRouteImport.update({
  id: "/aspect-ratio",
  path: "/aspect-ratio",
  getParentRoute: () => rootRouteImport,
} as any)
const AlertDialogRoute = AlertDialogRouteImport.update({
  id: "/alert-dialog",
  path: "/alert-dialog",
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: "/alert",
  path: "/alert",
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionRoute = AccordionRouteImport.update({
  id: "/accordion",
  path: "/accordion",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksSidebar07Route = BlocksSidebar07RouteImport.update({
  id: "/sidebar-07",
  path: "/sidebar-07",
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksSidebar01Route = BlocksSidebar01RouteImport.update({
  id: "/sidebar-01",
  path: "/sidebar-01",
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksLogin02Route = BlocksLogin02RouteImport.update({
  id: "/login-02",
  path: "/login-02",
  getParentRoute: () => BlocksRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/accordion": typeof AccordionRoute
  "/alert": typeof AlertRoute
  "/alert-dialog": typeof AlertDialogRoute
  "/aspect-ratio": typeof AspectRatioRoute
  "/avatar": typeof AvatarRoute
  "/badge": typeof BadgeRoute
  "/blocks": typeof BlocksRouteWithChildren
  "/breadcrumb": typeof BreadcrumbRoute
  "/button": typeof ButtonRoute
  "/button-group": typeof ButtonGroupRoute
  "/card": typeof CardRoute
  "/checkbox": typeof CheckboxRoute
  "/collapsible": typeof CollapsibleRoute
  "/combobox": typeof ComboboxRoute
  "/context-menu": typeof ContextMenuRoute
  "/dialog": typeof DialogRoute
  "/drawer": typeof DrawerRoute
  "/empty": typeof EmptyRoute
  "/field": typeof FieldRoute
  "/input": typeof InputRoute
  "/input-group": typeof InputGroupRoute
  "/input-otp": typeof InputOtpRoute
  "/item": typeof ItemRoute
  "/kbd": typeof KbdRoute
  "/label": typeof LabelRoute
  "/menu": typeof MenuRoute
  "/menubar": typeof MenubarRoute
  "/native-select": typeof NativeSelectRoute
  "/navigation-menu": typeof NavigationMenuRoute
  "/pagination": typeof PaginationRoute
  "/popover": typeof PopoverRoute
  "/preview-card": typeof PreviewCardRoute
  "/progress": typeof ProgressRoute
  "/radio": typeof RadioRoute
  "/scroll-area": typeof ScrollAreaRoute
  "/select": typeof SelectRoute
  "/separator": typeof SeparatorRoute
  "/sheet": typeof SheetRoute
  "/sidebar": typeof SidebarRoute
  "/skeleton": typeof SkeletonRoute
  "/slider": typeof SliderRoute
  "/spinner": typeof SpinnerRoute
  "/switch": typeof SwitchRoute
  "/table": typeof TableRoute
  "/tabs": typeof TabsRoute
  "/textarea": typeof TextareaRoute
  "/toast": typeof ToastRoute
  "/toggle": typeof ToggleRoute
  "/toggle-group": typeof ToggleGroupRoute
  "/tooltip": typeof TooltipRoute
  "/typography": typeof TypographyRoute
  "/blocks/login-02": typeof BlocksLogin02Route
  "/blocks/sidebar-01": typeof BlocksSidebar01Route
  "/blocks/sidebar-07": typeof BlocksSidebar07Route
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accordion": typeof AccordionRoute
  "/alert": typeof AlertRoute
  "/alert-dialog": typeof AlertDialogRoute
  "/aspect-ratio": typeof AspectRatioRoute
  "/avatar": typeof AvatarRoute
  "/badge": typeof BadgeRoute
  "/blocks": typeof BlocksRouteWithChildren
  "/breadcrumb": typeof BreadcrumbRoute
  "/button": typeof ButtonRoute
  "/button-group": typeof ButtonGroupRoute
  "/card": typeof CardRoute
  "/checkbox": typeof CheckboxRoute
  "/collapsible": typeof CollapsibleRoute
  "/combobox": typeof ComboboxRoute
  "/context-menu": typeof ContextMenuRoute
  "/dialog": typeof DialogRoute
  "/drawer": typeof DrawerRoute
  "/empty": typeof EmptyRoute
  "/field": typeof FieldRoute
  "/input": typeof InputRoute
  "/input-group": typeof InputGroupRoute
  "/input-otp": typeof InputOtpRoute
  "/item": typeof ItemRoute
  "/kbd": typeof KbdRoute
  "/label": typeof LabelRoute
  "/menu": typeof MenuRoute
  "/menubar": typeof MenubarRoute
  "/native-select": typeof NativeSelectRoute
  "/navigation-menu": typeof NavigationMenuRoute
  "/pagination": typeof PaginationRoute
  "/popover": typeof PopoverRoute
  "/preview-card": typeof PreviewCardRoute
  "/progress": typeof ProgressRoute
  "/radio": typeof RadioRoute
  "/scroll-area": typeof ScrollAreaRoute
  "/select": typeof SelectRoute
  "/separator": typeof SeparatorRoute
  "/sheet": typeof SheetRoute
  "/sidebar": typeof SidebarRoute
  "/skeleton": typeof SkeletonRoute
  "/slider": typeof SliderRoute
  "/spinner": typeof SpinnerRoute
  "/switch": typeof SwitchRoute
  "/table": typeof TableRoute
  "/tabs": typeof TabsRoute
  "/textarea": typeof TextareaRoute
  "/toast": typeof ToastRoute
  "/toggle": typeof ToggleRoute
  "/toggle-group": typeof ToggleGroupRoute
  "/tooltip": typeof TooltipRoute
  "/typography": typeof TypographyRoute
  "/blocks/login-02": typeof BlocksLogin02Route
  "/blocks/sidebar-01": typeof BlocksSidebar01Route
  "/blocks/sidebar-07": typeof BlocksSidebar07Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/accordion": typeof AccordionRoute
  "/alert": typeof AlertRoute
  "/alert-dialog": typeof AlertDialogRoute
  "/aspect-ratio": typeof AspectRatioRoute
  "/avatar": typeof AvatarRoute
  "/badge": typeof BadgeRoute
  "/blocks": typeof BlocksRouteWithChildren
  "/breadcrumb": typeof BreadcrumbRoute
  "/button": typeof ButtonRoute
  "/button-group": typeof ButtonGroupRoute
  "/card": typeof CardRoute
  "/checkbox": typeof CheckboxRoute
  "/collapsible": typeof CollapsibleRoute
  "/combobox": typeof ComboboxRoute
  "/context-menu": typeof ContextMenuRoute
  "/dialog": typeof DialogRoute
  "/drawer": typeof DrawerRoute
  "/empty": typeof EmptyRoute
  "/field": typeof FieldRoute
  "/input": typeof InputRoute
  "/input-group": typeof InputGroupRoute
  "/input-otp": typeof InputOtpRoute
  "/item": typeof ItemRoute
  "/kbd": typeof KbdRoute
  "/label": typeof LabelRoute
  "/menu": typeof MenuRoute
  "/menubar": typeof MenubarRoute
  "/native-select": typeof NativeSelectRoute
  "/navigation-menu": typeof NavigationMenuRoute
  "/pagination": typeof PaginationRoute
  "/popover": typeof PopoverRoute
  "/preview-card": typeof PreviewCardRoute
  "/progress": typeof ProgressRoute
  "/radio": typeof RadioRoute
  "/scroll-area": typeof ScrollAreaRoute
  "/select": typeof SelectRoute
  "/separator": typeof SeparatorRoute
  "/sheet": typeof SheetRoute
  "/sidebar": typeof SidebarRoute
  "/skeleton": typeof SkeletonRoute
  "/slider": typeof SliderRoute
  "/spinner": typeof SpinnerRoute
  "/switch": typeof SwitchRoute
  "/table": typeof TableRoute
  "/tabs": typeof TabsRoute
  "/textarea": typeof TextareaRoute
  "/toast": typeof ToastRoute
  "/toggle": typeof ToggleRoute
  "/toggle-group": typeof ToggleGroupRoute
  "/tooltip": typeof TooltipRoute
  "/typography": typeof TypographyRoute
  "/blocks/login-02": typeof BlocksLogin02Route
  "/blocks/sidebar-01": typeof BlocksSidebar01Route
  "/blocks/sidebar-07": typeof BlocksSidebar07Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accordion"
    | "/alert"
    | "/alert-dialog"
    | "/aspect-ratio"
    | "/avatar"
    | "/badge"
    | "/blocks"
    | "/breadcrumb"
    | "/button"
    | "/button-group"
    | "/card"
    | "/checkbox"
    | "/collapsible"
    | "/combobox"
    | "/context-menu"
    | "/dialog"
    | "/drawer"
    | "/empty"
    | "/field"
    | "/input"
    | "/input-group"
    | "/input-otp"
    | "/item"
    | "/kbd"
    | "/label"
    | "/menu"
    | "/menubar"
    | "/native-select"
    | "/navigation-menu"
    | "/pagination"
    | "/popover"
    | "/preview-card"
    | "/progress"
    | "/radio"
    | "/scroll-area"
    | "/select"
    | "/separator"
    | "/sheet"
    | "/sidebar"
    | "/skeleton"
    | "/slider"
    | "/spinner"
    | "/switch"
    | "/table"
    | "/tabs"
    | "/textarea"
    | "/toast"
    | "/toggle"
    | "/toggle-group"
    | "/tooltip"
    | "/typography"
    | "/blocks/login-02"
    | "/blocks/sidebar-01"
    | "/blocks/sidebar-07"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accordion"
    | "/alert"
    | "/alert-dialog"
    | "/aspect-ratio"
    | "/avatar"
    | "/badge"
    | "/blocks"
    | "/breadcrumb"
    | "/button"
    | "/button-group"
    | "/card"
    | "/checkbox"
    | "/collapsible"
    | "/combobox"
    | "/context-menu"
    | "/dialog"
    | "/drawer"
    | "/empty"
    | "/field"
    | "/input"
    | "/input-group"
    | "/input-otp"
    | "/item"
    | "/kbd"
    | "/label"
    | "/menu"
    | "/menubar"
    | "/native-select"
    | "/navigation-menu"
    | "/pagination"
    | "/popover"
    | "/preview-card"
    | "/progress"
    | "/radio"
    | "/scroll-area"
    | "/select"
    | "/separator"
    | "/sheet"
    | "/sidebar"
    | "/skeleton"
    | "/slider"
    | "/spinner"
    | "/switch"
    | "/table"
    | "/tabs"
    | "/textarea"
    | "/toast"
    | "/toggle"
    | "/toggle-group"
    | "/tooltip"
    | "/typography"
    | "/blocks/login-02"
    | "/blocks/sidebar-01"
    | "/blocks/sidebar-07"
  id:
    | "__root__"
    | "/"
    | "/accordion"
    | "/alert"
    | "/alert-dialog"
    | "/aspect-ratio"
    | "/avatar"
    | "/badge"
    | "/blocks"
    | "/breadcrumb"
    | "/button"
    | "/button-group"
    | "/card"
    | "/checkbox"
    | "/collapsible"
    | "/combobox"
    | "/context-menu"
    | "/dialog"
    | "/drawer"
    | "/empty"
    | "/field"
    | "/input"
    | "/input-group"
    | "/input-otp"
    | "/item"
    | "/kbd"
    | "/label"
    | "/menu"
    | "/menubar"
    | "/native-select"
    | "/navigation-menu"
    | "/pagination"
    | "/popover"
    | "/preview-card"
    | "/progress"
    | "/radio"
    | "/scroll-area"
    | "/select"
    | "/separator"
    | "/sheet"
    | "/sidebar"
    | "/skeleton"
    | "/slider"
    | "/spinner"
    | "/switch"
    | "/table"
    | "/tabs"
    | "/textarea"
    | "/toast"
    | "/toggle"
    | "/toggle-group"
    | "/tooltip"
    | "/typography"
    | "/blocks/login-02"
    | "/blocks/sidebar-01"
    | "/blocks/sidebar-07"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionRoute: typeof AccordionRoute
  AlertRoute: typeof AlertRoute
  AlertDialogRoute: typeof AlertDialogRoute
  AspectRatioRoute: typeof AspectRatioRoute
  AvatarRoute: typeof AvatarRoute
  BadgeRoute: typeof BadgeRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  BreadcrumbRoute: typeof BreadcrumbRoute
  ButtonRoute: typeof ButtonRoute
  ButtonGroupRoute: typeof ButtonGroupRoute
  CardRoute: typeof CardRoute
  CheckboxRoute: typeof CheckboxRoute
  CollapsibleRoute: typeof CollapsibleRoute
  ComboboxRoute: typeof ComboboxRoute
  ContextMenuRoute: typeof ContextMenuRoute
  DialogRoute: typeof DialogRoute
  DrawerRoute: typeof DrawerRoute
  EmptyRoute: typeof EmptyRoute
  FieldRoute: typeof FieldRoute
  InputRoute: typeof InputRoute
  InputGroupRoute: typeof InputGroupRoute
  InputOtpRoute: typeof InputOtpRoute
  ItemRoute: typeof ItemRoute
  KbdRoute: typeof KbdRoute
  LabelRoute: typeof LabelRoute
  MenuRoute: typeof MenuRoute
  MenubarRoute: typeof MenubarRoute
  NativeSelectRoute: typeof NativeSelectRoute
  NavigationMenuRoute: typeof NavigationMenuRoute
  PaginationRoute: typeof PaginationRoute
  PopoverRoute: typeof PopoverRoute
  PreviewCardRoute: typeof PreviewCardRoute
  ProgressRoute: typeof ProgressRoute
  RadioRoute: typeof RadioRoute
  ScrollAreaRoute: typeof ScrollAreaRoute
  SelectRoute: typeof SelectRoute
  SeparatorRoute: typeof SeparatorRoute
  SheetRoute: typeof SheetRoute
  SidebarRoute: typeof SidebarRoute
  SkeletonRoute: typeof SkeletonRoute
  SliderRoute: typeof SliderRoute
  SpinnerRoute: typeof SpinnerRoute
  SwitchRoute: typeof SwitchRoute
  TableRoute: typeof TableRoute
  TabsRoute: typeof TabsRoute
  TextareaRoute: typeof TextareaRoute
  ToastRoute: typeof ToastRoute
  ToggleRoute: typeof ToggleRoute
  ToggleGroupRoute: typeof ToggleGroupRoute
  TooltipRoute: typeof TooltipRoute
  TypographyRoute: typeof TypographyRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/typography": {
      id: "/typography"
      path: "/typography"
      fullPath: "/typography"
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tooltip": {
      id: "/tooltip"
      path: "/tooltip"
      fullPath: "/tooltip"
      preLoaderRoute: typeof TooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/toggle-group": {
      id: "/toggle-group"
      path: "/toggle-group"
      fullPath: "/toggle-group"
      preLoaderRoute: typeof ToggleGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/toggle": {
      id: "/toggle"
      path: "/toggle"
      fullPath: "/toggle"
      preLoaderRoute: typeof ToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/toast": {
      id: "/toast"
      path: "/toast"
      fullPath: "/toast"
      preLoaderRoute: typeof ToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/textarea": {
      id: "/textarea"
      path: "/textarea"
      fullPath: "/textarea"
      preLoaderRoute: typeof TextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tabs": {
      id: "/tabs"
      path: "/tabs"
      fullPath: "/tabs"
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/table": {
      id: "/table"
      path: "/table"
      fullPath: "/table"
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/switch": {
      id: "/switch"
      path: "/switch"
      fullPath: "/switch"
      preLoaderRoute: typeof SwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/spinner": {
      id: "/spinner"
      path: "/spinner"
      fullPath: "/spinner"
      preLoaderRoute: typeof SpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/slider": {
      id: "/slider"
      path: "/slider"
      fullPath: "/slider"
      preLoaderRoute: typeof SliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/skeleton": {
      id: "/skeleton"
      path: "/skeleton"
      fullPath: "/skeleton"
      preLoaderRoute: typeof SkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sidebar": {
      id: "/sidebar"
      path: "/sidebar"
      fullPath: "/sidebar"
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sheet": {
      id: "/sheet"
      path: "/sheet"
      fullPath: "/sheet"
      preLoaderRoute: typeof SheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/separator": {
      id: "/separator"
      path: "/separator"
      fullPath: "/separator"
      preLoaderRoute: typeof SeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/select": {
      id: "/select"
      path: "/select"
      fullPath: "/select"
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scroll-area": {
      id: "/scroll-area"
      path: "/scroll-area"
      fullPath: "/scroll-area"
      preLoaderRoute: typeof ScrollAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/radio": {
      id: "/radio"
      path: "/radio"
      fullPath: "/radio"
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/progress": {
      id: "/progress"
      path: "/progress"
      fullPath: "/progress"
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview-card": {
      id: "/preview-card"
      path: "/preview-card"
      fullPath: "/preview-card"
      preLoaderRoute: typeof PreviewCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/popover": {
      id: "/popover"
      path: "/popover"
      fullPath: "/popover"
      preLoaderRoute: typeof PopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pagination": {
      id: "/pagination"
      path: "/pagination"
      fullPath: "/pagination"
      preLoaderRoute: typeof PaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/navigation-menu": {
      id: "/navigation-menu"
      path: "/navigation-menu"
      fullPath: "/navigation-menu"
      preLoaderRoute: typeof NavigationMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/native-select": {
      id: "/native-select"
      path: "/native-select"
      fullPath: "/native-select"
      preLoaderRoute: typeof NativeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/menubar": {
      id: "/menubar"
      path: "/menubar"
      fullPath: "/menubar"
      preLoaderRoute: typeof MenubarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/menu": {
      id: "/menu"
      path: "/menu"
      fullPath: "/menu"
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/label": {
      id: "/label"
      path: "/label"
      fullPath: "/label"
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kbd": {
      id: "/kbd"
      path: "/kbd"
      fullPath: "/kbd"
      preLoaderRoute: typeof KbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/item": {
      id: "/item"
      path: "/item"
      fullPath: "/item"
      preLoaderRoute: typeof ItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/input-otp": {
      id: "/input-otp"
      path: "/input-otp"
      fullPath: "/input-otp"
      preLoaderRoute: typeof InputOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/input-group": {
      id: "/input-group"
      path: "/input-group"
      fullPath: "/input-group"
      preLoaderRoute: typeof InputGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/input": {
      id: "/input"
      path: "/input"
      fullPath: "/input"
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/field": {
      id: "/field"
      path: "/field"
      fullPath: "/field"
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/empty": {
      id: "/empty"
      path: "/empty"
      fullPath: "/empty"
      preLoaderRoute: typeof EmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/drawer": {
      id: "/drawer"
      path: "/drawer"
      fullPath: "/drawer"
      preLoaderRoute: typeof DrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dialog": {
      id: "/dialog"
      path: "/dialog"
      fullPath: "/dialog"
      preLoaderRoute: typeof DialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/context-menu": {
      id: "/context-menu"
      path: "/context-menu"
      fullPath: "/context-menu"
      preLoaderRoute: typeof ContextMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/combobox": {
      id: "/combobox"
      path: "/combobox"
      fullPath: "/combobox"
      preLoaderRoute: typeof ComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/collapsible": {
      id: "/collapsible"
      path: "/collapsible"
      fullPath: "/collapsible"
      preLoaderRoute: typeof CollapsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkbox": {
      id: "/checkbox"
      path: "/checkbox"
      fullPath: "/checkbox"
      preLoaderRoute: typeof CheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/card": {
      id: "/card"
      path: "/card"
      fullPath: "/card"
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/button-group": {
      id: "/button-group"
      path: "/button-group"
      fullPath: "/button-group"
      preLoaderRoute: typeof ButtonGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/button": {
      id: "/button"
      path: "/button"
      fullPath: "/button"
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/breadcrumb": {
      id: "/breadcrumb"
      path: "/breadcrumb"
      fullPath: "/breadcrumb"
      preLoaderRoute: typeof BreadcrumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/blocks": {
      id: "/blocks"
      path: "/blocks"
      fullPath: "/blocks"
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/badge": {
      id: "/badge"
      path: "/badge"
      fullPath: "/badge"
      preLoaderRoute: typeof BadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/avatar": {
      id: "/avatar"
      path: "/avatar"
      fullPath: "/avatar"
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/aspect-ratio": {
      id: "/aspect-ratio"
      path: "/aspect-ratio"
      fullPath: "/aspect-ratio"
      preLoaderRoute: typeof AspectRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alert-dialog": {
      id: "/alert-dialog"
      path: "/alert-dialog"
      fullPath: "/alert-dialog"
      preLoaderRoute: typeof AlertDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/alert": {
      id: "/alert"
      path: "/alert"
      fullPath: "/alert"
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accordion": {
      id: "/accordion"
      path: "/accordion"
      fullPath: "/accordion"
      preLoaderRoute: typeof AccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/blocks/sidebar-07": {
      id: "/blocks/sidebar-07"
      path: "/sidebar-07"
      fullPath: "/blocks/sidebar-07"
      preLoaderRoute: typeof BlocksSidebar07RouteImport
      parentRoute: typeof BlocksRoute
    }
    "/blocks/sidebar-01": {
      id: "/blocks/sidebar-01"
      path: "/sidebar-01"
      fullPath: "/blocks/sidebar-01"
      preLoaderRoute: typeof BlocksSidebar01RouteImport
      parentRoute: typeof BlocksRoute
    }
    "/blocks/login-02": {
      id: "/blocks/login-02"
      path: "/login-02"
      fullPath: "/blocks/login-02"
      preLoaderRoute: typeof BlocksLogin02RouteImport
      parentRoute: typeof BlocksRoute
    }
  }
}

interface BlocksRouteChildren {
  BlocksLogin02Route: typeof BlocksLogin02Route
  BlocksSidebar01Route: typeof BlocksSidebar01Route
  BlocksSidebar07Route: typeof BlocksSidebar07Route
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksLogin02Route: BlocksLogin02Route,
  BlocksSidebar01Route: BlocksSidebar01Route,
  BlocksSidebar07Route: BlocksSidebar07Route,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionRoute: AccordionRoute,
  AlertRoute: AlertRoute,
  AlertDialogRoute: AlertDialogRoute,
  AspectRatioRoute: AspectRatioRoute,
  AvatarRoute: AvatarRoute,
  BadgeRoute: BadgeRoute,
  BlocksRoute: BlocksRouteWithChildren,
  BreadcrumbRoute: BreadcrumbRoute,
  ButtonRoute: ButtonRoute,
  ButtonGroupRoute: ButtonGroupRoute,
  CardRoute: CardRoute,
  CheckboxRoute: CheckboxRoute,
  CollapsibleRoute: CollapsibleRoute,
  ComboboxRoute: ComboboxRoute,
  ContextMenuRoute: ContextMenuRoute,
  DialogRoute: DialogRoute,
  DrawerRoute: DrawerRoute,
  EmptyRoute: EmptyRoute,
  FieldRoute: FieldRoute,
  InputRoute: InputRoute,
  InputGroupRoute: InputGroupRoute,
  InputOtpRoute: InputOtpRoute,
  ItemRoute: ItemRoute,
  KbdRoute: KbdRoute,
  LabelRoute: LabelRoute,
  MenuRoute: MenuRoute,
  MenubarRoute: MenubarRoute,
  NativeSelectRoute: NativeSelectRoute,
  NavigationMenuRoute: NavigationMenuRoute,
  PaginationRoute: PaginationRoute,
  PopoverRoute: PopoverRoute,
  PreviewCardRoute: PreviewCardRoute,
  ProgressRoute: ProgressRoute,
  RadioRoute: RadioRoute,
  ScrollAreaRoute: ScrollAreaRoute,
  SelectRoute: SelectRoute,
  SeparatorRoute: SeparatorRoute,
  SheetRoute: SheetRoute,
  SidebarRoute: SidebarRoute,
  SkeletonRoute: SkeletonRoute,
  SliderRoute: SliderRoute,
  SpinnerRoute: SpinnerRoute,
  SwitchRoute: SwitchRoute,
  TableRoute: TableRoute,
  TabsRoute: TabsRoute,
  TextareaRoute: TextareaRoute,
  ToastRoute: ToastRoute,
  ToggleRoute: ToggleRoute,
  ToggleGroupRoute: ToggleGroupRoute,
  TooltipRoute: TooltipRoute,
  TypographyRoute: TypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
